services:
  - type: web
    name: infisical
    plan: free
    region: singapore
    env: docker
    dockerfilePath: ./Dockerfile.standalone-infisical
    autoDeploy: true
    # healthCheckPath: /api/status
    repo: https://github.com/Infisical/infisical.git
    envVars:
      - fromGroup: infisical-grp
      - key: PORT
        value: 443
