services:
  - type: web
    name: infisical
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile.standalone-infisical
    autoDeploy: false
    # healthCheckPath: /api/status
    repo: https://github.com/Infisical/infisical.git
    envVarGroups:
      - name: infisical.env
        envVars:
          - key: PORT
            value: 443
